apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.names.api }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "todolist.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: {{ .Values.service.apiType }}

