apiVersion: v1
kind: Pod
metadata:
  name: backups-inspector
spec:
  restartPolicy: Always
  containers:
    - name: sh
      image: busybox
      command: ["sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: backups
          mountPath: /backups
  volumes:
    - name: backups
      persistentVolumeClaim:
        claimName: todolist-backups

