{{- if and .Values.backup.enabled .Values.backup.inspector.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "todolist.fullname" . }}-backups-inspector
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  restartPolicy: Always
  containers:
    - name: sh
      image: {{ .Values.backup.inspector.image | default "busybox:1.36" }}
      command: ["sh", "-c", "sleep 36000"]
      volumeMounts:
        - name: backups
          mountPath: /backups
  volumes:
    - name: backups
      persistentVolumeClaim:
        claimName: {{ include "todolist.fullname" . }}-backups
{{- end }}
