apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.names.frontend }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
