apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todolist.fullname" . }}-mariadb
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "todolist.fullname" . }}-mariadb-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mariadb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - containerPort: {{ .Values.mariadb.port }}
          env:
            - name: MARIADB_ROOT_HOST
              value: "%"
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist.fullname" . }}-config
                  key: MYSQL_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.fullname" . }}-secret
                  key: MYSQL_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.fullname" . }}-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist.fullname" . }}-config
                  key: MYSQL_DB
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mariadb.storage }}
