apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: movies.cndw.mta.io
spec:
  group: cndw.mta.io
  scope: Namespaced
  names:
    plural: movies
    singular: movie
    kind: Movie
    shortNames:
      - mv
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["title", "year"]
              properties:
                title:
                  type: string
                year:
                  type: integer
                director:
                  type: string
                genres:
                  type: array
                  items:
                    type: string
                rating:
                  type: number
                watched:
                  type: boolean
