apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.fullname" . }}-secret
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "MY_SQL_ROOT_PASSWORD is required" .Values.MY_SQL_ROOT_PASSWORD | b64enc | quote }}  