apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.fullname" . }}-secret
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ default "abcdef" .Values.mariadb.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
